"""create database

Revision ID: 0fc8c87ae9ac
Revises: 
Create Date: 2022-08-02 21:10:41.927116

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0fc8c87ae9ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('phone_number', sa.Unicode(length=25), nullable=False),
    sa.Column('email', sa.Unicode(length=255), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_couriers'))
    )
    with op.batch_alter_table('couriers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_couriers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_couriers_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_couriers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_couriers_phone_number'), ['phone_number'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Unicode(length=128), nullable=False),
    sa.Column('sender_name', sa.Unicode(length=255), nullable=False),
    sa.Column('receiver_name', sa.Unicode(length=255), nullable=False),
    sa.Column('receiver_address', sa.Unicode(length=255), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], name=op.f('fk_orders_courier_id_couriers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_id'), ['id'], unique=True)

    op.create_table('orders_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.Unicode(length=255), nullable=False),
    sa.Column('item_qty', sa.Float(), nullable=True),
    sa.Column('qty_unit', sa.Unicode(length=255), nullable=True),
    sa.Column('item_price', sa.Float(), nullable=False),
    sa.Column('item_desc', sa.Unicode(length=255), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_orders_details_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders_details'))
    )
    with op.batch_alter_table('orders_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_details_id'), ['id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_details_id'))

    op.drop_table('orders_details')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_id'))

    op.drop_table('orders')
    with op.batch_alter_table('couriers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_couriers_phone_number'))
        batch_op.drop_index(batch_op.f('ix_couriers_is_active'))
        batch_op.drop_index(batch_op.f('ix_couriers_id'))
        batch_op.drop_index(batch_op.f('ix_couriers_email'))

    op.drop_table('couriers')
    # ### end Alembic commands ###
